global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: neuroplc
    static_configs:
      - targets: ["host.docker.internal:9100"]

  - job_name: cortex
    static_configs:
      - targets: ["host.docker.internal:8080"]
